name: Holiday Extras - Hungry Geek
description: Holiday Extras Geek Blog
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
url: http://holidayextras.github.com
baseurl: 
paginate: 10
gems:
  - jekyll-redirect-from
prose:
  rooturl: '_posts'
  siteurl: 'http://holidayextras.github.io/'
  ignore:
    - index.html
    - feed.xml
    - holidayextras.sublime-project
    - .gitignore
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - /projects
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"  
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "comments"
        field:
          element: "hidden"
          value: "true"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Your full name"
      - name: "title"
        field:
          element: "text"
          type: "text"
          label: "Blog title"
      - name: "categories"
        field:
          element: "text"
          type: "text"
          placeholder: "NodeJS"
          label: "Categories"
      - name: "tags"
        field:
          element: "text"
          type: "text"
          label: "Searchable tags"